# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1069b776749fc44578355645a57b02798c3e4384b99410925cc8e76a317502030c868fa92e7164544a8a2d4c0d137379ec7db50d3814a454a017348a6c5893a4

test:
  secret_key_base: b23d404def0e48e201dbb8247e7b9d334cb732ef77c0f6e57031f13d67bc212d79b710fc56d2129ba02ef09cdfbd123e81b963bee19c6e996a37bfc6482cb13a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
